version: '3'
services:
  discovery:
    build: eurekaserver
    container_name: discovery
    ports:
      - 8761:8761
    networks: 
      - message_network
  gateway: 
    build: cloudgateway
    container_name: gateway
    environment:
        - JAVA_OPTS=
          -DEUREKA_SERVER=http://discovery:8761/eureka
    ports:
        - 9191:9191 
    depends_on: 
        - discovery
    networks: 
      - message_network
  stock:
    build: stock
    container_name: stock
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
      - DB_OPTS=
        -Dspring.data.mongodb.uri=mongodb://mongo:27017/stockmarket
    ports: 
        - 9002:9002
    depends_on:
      - discovery
      - mongo
    links: 
        - mongo
    networks: 
      - message_network
  mongo:
    image: 'mongo'
    ports: 
        - 27017:27017
    container_name: mongo
    volumes: 
        - ./data/db:/data/db
    networks: 
      - message_network
  company:
    build: company
    container_name: company
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
      - DB_OPTS=
        -Dspring.data.mongodb.uri=mongodb://mongo:27017/stockmarket
    ports: 
        - 9001:9001
    depends_on:
      - discovery
      - mongo  
    links: 
        - mongo
    networks: 
      - message_network
  angular:
    hostname: localhost
    container_name: angular
    build: Angular_UI/StockMarket
    ports: 
        - 8181:80
    networks: 
      - message_network
networks: 
  message_network:
    external: 
      name: eventmessage
