server:
  port: 9002


spring:
  application:
    name: STOCK-SERVICE
  data:
    mongodb:
      host: mongo
      #host: localhost
      port: 27017
      database: stockmarket

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      hostname: localhost